### ISSUE TITLE
KubernetesEndpointResolver only works in Legacy mode for v1.14

### ISSUE THREAD

**Issue by dnlbyl** [emissary-ingress/emissary#4186] opened 2022-04-08 19:07 UTC
**Describe the bug**

- We were on 1.3.0, migrating to 1.14.3 (via YAML).
- We use `KubernetesEndpointResolver` and `resolver: endpoint policy: roundrobin` in our Mappings to utilize pod IPs in the resulting envoy config vs Kubernetes dns.
- With the resolver setup, we managed to get near zero downtime deploys with 1.3.0.
- **With 1.14.3 we started experiencing 503s during rolling updates to backend services, for up to 10 minutes after the update.**

The underlying issue appears to be that the Envoy config being generated is now using `"type": "EDS"` instead of `"type": "STRICT_DNS"`. I have tracked this down to this conditional: https://github.com/emissary-ingress/emissary/blob/9cdbc6bf3733eef800883f72d05f621be97cec96/python/ambassador/envoy/v2/v2cluster.py#L52-L60

Setting `AMBASSADOR_LEGACY_MODE` to `true` on 1.14.3 results in the desired behavior (aligning with the `Config.legacy_mode` part of the above code).

**Expected behavior**
Using a `KubernetesEndpointResolver` does not switch Envoy to `EDS` without needing to set `AMBASSADOR_LEGACY_MODE` to `true`.

Note that the Change log for 1.14.2 states:

> Feature: You can now set dns_type in Ambassador Mappings to use Envoy’s logical_dns resolution instead of the default strict_dns.

The behavior we are expereince does not align with this. 

**Versions (please complete the following information):**
 - Ambassador: 1.14.3
 - Kubernetes version: 1.22

**Additional context**

#3897 might be related.

**Comment by dnlbyl** [comment] 2022-04-13 16:48
I've been testing v2.2.2 and the issue is worse there as AMBASSADOR_LEGACY_MODE no longer has any effect. 

https://github.com/emissary-ingress/emissary/blob/a9b94f457162f8d6fb3ef66bff7b9f89e7ba2d53/python/ambassador/envoy/v2/v2cluster.py#L52-L60

This means that if a `KubernetesEndpointResolver` is used with v2.2.2 it will always configure Envoy to use `EDS` mode for service discovery. 

`EDS` mode does not behave well for use during backend service rollouts, and it does not appear to be a supported option according to the [emissary docs](https://www.getambassador.io/docs/emissary/latest/topics/using/mappings/#using-dns_type) where only `strict_dns` and `logical_dns` are mentioned as options. 

Previously we found that an `KubernetesEndpointResolver` gave us the best results during a backend rollout (i.e. lowest incidents of 503s due to envoy directing to terminated pods).

**Comment by cindymullins-dw** [comment] 2022-12-24 01:19
In [2.4](https://www.getambassador.io/docs/emissary/latest/release-notes#2.4.0) and [3.2 ](https://www.getambassador.io/docs/emissary/latest/release-notes#3.2.0) we made a fix to allow bypassing of EDS for manual endpoint insertion to address 503UH errors related to cert rotation.  Could you let us know if that improved this issue?

**Comment by joshbranham** [comment] 2022-12-27 14:15
We are currently running 2.5 and have abandoned using `KubernetesEndpointResolver` altogether, so I have no way to test if a fix worked. Feel free to close this if you feel you have addressed the cause.

**Closed** 2023-04-13 23:40 UTC
Labels: t:bug
