### ISSUE TITLE
Deploying Emissary ingress 2.X on GKE with L7 load balancer 

### ISSUE THREAD

**Issue by charuhans** [emissary-ingress/emissary#4166] opened 2022-03-15 15:59 UTC
Hello,

I am trying to deploy Emissary ingress 2.2.2 on GKE with google L7 load balancer . I am following the guide here: https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador-with-gke/. My health checks are:
`
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: test-ingress-bc
  namespace: dataiku-dev
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  timeoutSec: 600
  logging:
    enable: true
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /ambassador/v0/check_ready
    port: 8877

My ingress is :
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: certificate-2021
    ingress.kubernetes.io/ssl-cert: certificate-2021
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: test-ingress-address
    kubernetes.io/tls-acme: "true"
    networking.gke.io/v1beta1.FrontendConfig: test-ingress-fc
spec:
  defaultBackend:
    service:
      name: emissary-ingress
      port:
        number: 80

Since version 2.X has made Listener mandatory (https://www.getambassador.io/docs/emissary/latest/about/changes-2.x/), I have a created a Listener and host as described here for l7: https://www.getambassador.io/docs/edge-stack/latest/howtos/configure-communications/#using-an-l7-load-balancer-to-terminate-tls

apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: lb-listener
spec:
  port: 8443
  protocol: HTTP
  securityModel: XFP
  l7Depth: 1
  hostBinding:     
    namespace:
      from: SELF

apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: minimal-host
spec:
  hostname: test.com
  requestPolicy:
    insecure:
      action: Redirect

Issue:
Loadbalancer health checks are unhealthy. Am I missing anything from configuration side?
This is what I see in Routes:

![image](https://user-images.githubusercontent.com/1617592/158419292-daa47b36-2b2e-44d1-b3d0-578c5f103a3e.png)

**Comment by AliceProxy** [comment] 2022-03-21 18:50
Hi @charuhans 

I'm closing this issue since the issues section of Emissary Ingress is only for bug reports and feature requests. If you need help configuring Emissary then you can post your question in the [Ambassador Labs Community Slack channel](https://a8r.io/slack) where other users and Ambassador employees can help you with configuration issues in the `#emissary` channel. 

If you discover that the issue you are encountering is the cause of a bug in Emissary Ingress then please re-create your issue following the provided template with a clear and concise description of what the bug is, steps that can be followed to reproduce the behavior, and a description of the expected behavior. 

Thank you.

**Closed by AliceProxy** 2022-03-21 18:50 UTC
