### ISSUE TITLE
TLS Context requires wildcard host

### ISSUE THREAD

**Issue by blhagadorn** [emissary-ingress/emissary#3171] opened 2021-01-21 21:54 UTC
**Describe the bug**
Similar to this issue (the comments at the end): https://github.com/datawire/ambassador/issues/2252 
When setting up a gRPC client speaking to an upstream gRPC server, and using the upstream TLS configuration (as specified in the gRPC getting started guide: https://www.getambassador.io/docs/latest/howtos/grpc/), envoy  
configuration doesn't show the correct cluster.  When TLS Context is set to '*', things work correctly:
I would expect this to work:
```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: upstream
spec:
  alpn_protocols: h2
  ambassador_id:
  - "public"
  hosts:
  - 'grpc-example.example.com:443'
  secret: grpc-example-self-signed-cert
```
However, only this works:
```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: upstream
spec:
  alpn_protocols: h2
  ambassador_id:
  - "public"
  hosts:
  - '*'
  secret: grpc-example-self-signed-cert
```

**To Reproduce**
1. Create gRPC client and server with TLS Context specified
**Expected behavior**
That the first TLS Context works.

**Versions (please complete the following information):**
 - Ambassador: 1.8.1
 - Kubernetes environment : EKS
 - Version: 1.17

**Additional context**
The Diagnostics UI complains about this setup, even though it works (since the hosts don't match).
Maybe related, however we only have one TLS Context in the cluster: https://github.com/datawire/ambassador/issues/2403

**Comment by blhagadorn** [comment] 2021-01-27 08:01
I guess if this is the necessary YAML for the desired outcome, is there any downside? Other than the error in the Diagnostics UI? @nbkrause have you seen this issue by chance? Would be happy to reproduce it for the team.

**Comment by cakuros** [comment] 2021-02-15 15:40
Hi @blhagadorn.  As a followup to our discussion, when it comes to `TLSContexts`, there's an idea of "upstream" and "downstream" `TLSContexts`.  In the "downstream" use case, a `TLSContext` is used to manage TLS handshakes from a client to Ambassador.  This can include anything from simply specifying ALPN protocols to full `mTLS` and client certificate validation.  The way to identify and ensure that a `TLSContext` is a "downstream" `TLSContext` is if it is attached to a `Host` resource.  There are a few ways to do this as described here: https://www.getambassador.io/docs/latest/topics/running/tls/#host-and-tlscontext.  Because Ambassador sees you're trying to use `grpc-example.example.com:443` as a hostname, and sees that you have a `Host` using that hostname, it thinks you're trying to implicitly link the two.

A `TLSContext` that specifies the same hostname in its `spec.hosts` as an existing `Host` hostname, but is not linked is considered invalid configuration.  Implicit `TLSContext` linking is not supported as of the current version of Ambassador.

For your use case, you want to use an "upstream" `TLSContext`.  Similarly to how a `Host` connects to a `TLSContext` to make a "downstream" context, connecting a `TLSContext` to a `Mapping` creates an "upstream" `TLSContext`.  When you remove the `grpc-example.example.com:443` and replace it with a `*`, Ambassador no longer assumes that you're trying to use this `TLSContext` implicitly and so the error disappears.  For more info about "upstream" TLSContexts, see: https://www.getambassador.io/docs/latest/topics/running/tls/origination/#advanced-configuration-using-a-tlscontext.

**Comment by cindymullins-dw** [comment] 2022-07-30 06:45
Closing with this explanation of expected behavior above.

**Closed by cindymullins-dw** 2022-07-30 06:45 UTC
