### ISSUE TITLE
Set-cookie header and custom headers are being passed down to upstream services when using emissary authservice.

### ISSUE THREAD

**Issue by alfrye** [emissary-ingress/emissary#4381] opened 2022-08-05 15:26 UTC
**Describe the bug**
When emissary has the authservice module enabled for external authentication, any cookie 
or header that I set in my authservice does not make to the upstream service.

**To Reproduce**
1. Create an auth service server(installed in the kubernetes cluster) and in the authservice set cookie headers
2. add the following emissary configuration.

```
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentication
  namespace: api-gateway
spec:
  auth_service: "http://auth-service.blueframe:9000"
   path_prefix: "/bfauth"
  allowed_request_headers:
   - x-myheader
  allowed_authorization_headers:
   - set-cookie
   - x-myheader
```
  

4. use http navigate to upsteam service
5. inspect request headers 

**Expected behavior**
I would expect that the headers and cookie that I set in the auth service code will be included in the 
request set to the upstream service. 

**Versions (please complete the following information):**
 - Ambassador: emissary ingress 3.1.0
 - Kubernetes environment k3s
 - Version: 1.21.4

**Comment by alfrye** [comment] 2022-08-05 15:31
From inside my cluster, I was able to bypass emissary by accessing the authentication endpoint using curl and was to see the headers being set.


```
Host: auth-service.blueframe:9000
> User-Agent: curl/7.55.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Set-Cookie: BLUEFRAME_SESSION=test+data+; Path=/; Max-Age=86400; HttpOnly; Secure
< X-Myheader: test
< Date: Fri, 05 Aug 2022 03:02:21 GMT
< Content-Length: 0
```

**Comment by alfrye** [comment] 2022-08-05 16:58
Updated:
I enabled trace logs with in envoy and ran test again. I am able to see the set cookie in the envoy logs but in the browser 

`set-cookie', 'BLUEFRAME_SESSION=%7B%0A++++%22TokenResponse%22%3A+%7B%0A++++++++%22access_token%22%3A+%22eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzY2cyM21BRHlXeVpUVzdWcy00VWJaNS13TEtsSEI4UlhaU25oU0NYekhvIn0.eyJleHAiOjE2NTk3MTg5MDQsImlhdCI6MTY1OTcxODYwNCwiYXV0aF90aW1lIjoxNjU5NzE4NjA0LCJqdGkiOiJiYTM2NGY5MC00OWQ0LTRjYjYtOWQ1OS1mY2YwNzJhMDYzYTAiLCJpc3MiOiJodHRwczovLzEwLjM5LjgzLjI1My9hdXRoL3JlYWxtcy9ibHVlZnJhbWUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYjVmMTUwMjktZDMwYi00NmRhLThlNjEtNGM3NWZlM2Y5NjNmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGVtb2FwcCIsInNlc3Npb25fc3RhdGUiOiI5YjJlNWU5ZC1mYzEwLTRiNWMtOTUzZS0zODcyMmRlYTY3YTMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vMTAuMzkuODMuMjUzIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWJsdWVmcmFtZSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiOWIyZTVlOWQtZmMxMC00YjVjLTk1M2UtMzg3MjJkZWE2N2EzIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJBbGFuIEZyeWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGFuIiwiZ2l2ZW5fbmFtZSI6IkFsYW4iLCJmYW1pbHlfbmFtZSI6IkZyeWUiLCJlbWFpbCI6ImFsYW5fZnJ5ZUBzZWxpbmMuY29tIn0.BP6LB_P27z5m4xByQuUNUdPUudu178XisYj-cbP6FXuKFPGD2mvlX8yNu-OOxUAVDoWq-6fDTnhqBhHHTFZlN5fZSGBKkNcoGlwxnOFpOPDFSjGHPgwxgjpyM__4D9Dwpp_QjwzuHdaSzGU--eQ9HwY3v-b1YwrNMPdtFpBgc5RAbKhXBqfEM3J0fm4_-HYuRlWp-cQjv4FEBw-u7l9Eg88LSuJKXCReMcdj-6jCzfK9hV-aU3pvtDHn0P9VBkqJZl_o5QGwhrPo2syMJd_xPaZHxLNXyQtAXZ6P4NpiIk7ffgY3Urd7VSJ_i6PmG5DJST2M6t8NibJV3ZrKT_nsdw%22%2C%0A++++++++%22token_type%22%3A+%22Bearer%22%2C%0A++++++++%22refresh_token%22%3A+%22eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1OWY0Nzc0My1kYmIwLTQ5MTUtOGNiMS1lMGFlYjUxMzk3MGMifQ.eyJleHAiOjE2NTk3MjA0MDQsImlhdCI6MTY1OTcxODYwNCwianRpIjoiNzRlODVhMGYtZjA3Ny00Mjg1LTgwMmMtNjViZDE2MzA0ODFjIiwiaXNzIjoiaHR0cHM6Ly8xMC4zOS44My4yNTMvYXV0aC9yZWFsbXMvYmx1ZWZyYW1lIiwiYXVkIjoiaHR0cHM6Ly8xMC4zOS44My4yNTMvYXV0aC9yZWFsbXMvYmx1ZWZyYW1lIiwic3ViIjoiYjVmMTUwMjktZDMwYi00NmRhLThlNjEtNGM3NWZlM2Y5NjNmIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImRlbW9hcHAiLCJzZXNzaW9uX3N0YXRlIjoiOWIyZTVlOWQtZmMxMC00YjVjLTk1M2UtMzg3MjJkZWE2N2EzIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjliMmU1ZTlkLWZjMTAtNGI1Yy05NTNlLTM4NzIyZGVhNjdhMyJ9.3mo7h-OdBGYP6NPIIWnw_umLsnuY620Wr1oLDYk5PGY%22%2C%0A++++++++%22expiry%22%3A+%222022-08-05T17%3A01%3A44.550335699Z%22%0A++++%7D%2C%0A++++%22IDToken%22%3A+%7B%0A++++++++%22exp%22%3A+1659718904%2C%0A++++++++%22iat%22%3A+1659718604%2C%0A++++++++%22auth_time%22%3A+1659718604%2C%0A++++++++%22jti%22%3A+%2200ee64d0-4ac1-4320-aab6-bac44dd65829%22%2C%0A++++++++%22iss%22%3A+%22https%3A%2F%2F10.39.83.253%2Fauth%2Frealms%2Fblueframe%22%2C%0A++++++++%22aud%22%3A+%22demoapp%22%2C%0A++++++++%22sub%22%3A+%22b5f15029-d30b-46da-8e61-4c75fe3f963f%22%2C%0A++++++++%22typ%22%3A+%22ID%22%2C%0A++++++++%22azp%22%3A+%22demoapp%22%2C%0A++++++++%22session_state%22%3A+%229b2e5e9d-fc10-4b5c-953e-38722dea67a3%22%2C%0A++++++++%22at_hash%22%3A+%22U-p0-bLr2nV7sZBtoi98WQ%22%2C%0A++++++++%22acr%22%3A+%221%22%2C%0A++++++++%22sid%22%3A+%229b2e5e9d-fc10-4b5c-953e-38722dea67a3%22%2C%0A++++++++%22email_verified%22%3A+true%2C%0A++++++++%22name%22%3A+%22Alan+Frye%22%2C%0A++++++++%22preferred_username%22%3A+%22alan%22%2C%0A++++++++%22given_name%22%3A+%22Alan%22%2C%0A++++++++%22family_name%22%3A+%22Frye%22%2C%0A++++++++%22email%22%3A+%22alan_frye%40selinc.com%22%0A++++%7D%0A%7D; Path=/; Max-Age=86400; HttpOnly; Secure'`

**Comment by cindymullins-dw** [comment] 2022-08-08 20:31
@alfrye, in the Module config can you try including `exposed_headers` (example below) in addition to `allowed_headers`?  For use with set_cookie it looks like you’ll need both of these in your Module.

```
cors:
        credentials: true
        exposed_headers:
        - Set-Cookie
        headers:
        - Set-Cookie

```
It also seems that set_cookie is very particular and that you may need to add some CORS/set_cookie logit to your application as well.  Please see [this link ](https://www.mezhenskyi.dev/blog/post/CORS%20Policy%20%26%20Set-Cookie%20Explained)for more context.

**Comment by alfrye** [comment] 2022-08-12 20:09
After adding cors config, I am still not getting the cookie header. my update mapping looks like this 

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: demoapp-mapping
  namespace: demo
spec:
  prefix: /demoapp/status/
  rewrite: /status
  cors:
    origins: https://10.39.83.253
    methods: POST, GET, OPTIONS
    headers:
    - set-cookie
    credentials: true
    exposed_headers:
    - X-Custom-Header
    - set-cookie
    - x-myheader
    max_age: "86400"
  service: http://demoapp.demo:8585
  #bypass_auth: true

```
Next Step:
I am going put together a sample code setup that I can share in order for us to troubleshoot this further.

**Comment by alfrye** [comment] 2022-08-23 19:25
I have added the examples I am using to the following github repo for reference.  `https://github.com/alfrye/authdemo`
The repo contains 2 apps one called demoapp which is the endpoints I am trying to authenticate for.  The second app is a simple authservice that has one endpoint and all it does currently is sets a cookie and returns an http 200 back to emissary, which forwards the request to app1. However, the cookie is not being sent to app1

**Comment by cindymullins-dw** [comment] 2022-09-09 21:55
Hi @alfrye, would you take a look at [this previous issue](https://github.com/emissary-ingress/emissary/issues/1173) and note the AuthService config there?  Might be worth trying 'allowed_headers' and note cookies there rather than allowed_authorization_headers'

**Comment by alfrye** [comment] 2023-04-19 20:17
I am still experiencing this issue, that my set-cookie header from the AuthService is not being passed down from emissary to the application. Any suggestions would be greatly appreciated

**Comment by cindymullins-dw** [comment] 2023-06-13 20:24
Hi @alfrye, can you try removing this below from allowed_authorization_headers on the AuthService?
   - set-cookie

The cookie should be set automatically so perhaps this is creating a conflict, [docs ref below](https://www.getambassador.io/docs/edge-stack/latest/topics/running/services/auth-service#fields)
allowed_request_headers | [] | Lists the headers (case-insensitive) that are copied from the incoming request to the request made to the external auth service. In addition to the headers listed in this field, the following headers are always included: Authorization, Cookie, From, Proxy-Authorization, User-Agent, X-Forwarded-For, X-Forwarded-Host, and X-Forwarded-Proto.

**Comment by cindymullins-dw** [comment] 2023-06-14 19:03
Thanks for trying that although you noted in our Slack there was no impact.  We did notice your Kubernetes is 1.21 although you're using Emissary 3.1.  For the Emissary 3.x series we'd recommend an upgrade to Kubernetes 1.22 but that's probably not the cause of this issue.  Since you're seeing the set cookie in the Envoy logs we believe Emissary is processing and sending it correctly.  Could there be other reasons it's not showing up in the browser, something like [this](https://stackoverflow.com/questions/36824106/express-doesnt-set-a-cookie/42735038#42735038) perhaps?

**Comment by alfrye** [comment] 2023-06-14 20:45
Hi @cindymullins-dw Thanks for the reply.

I have recently upgraded to Kubernetes v1.25.3+k3s1 version. I have also noticed that If I attempt to hit a route that is by passing the authservice the cookie gets set and is visible in the browser. Only when the request is routed through to my authservice endpoint does the cookie not get passed through.

Here are the headers that are getting set on the request

`GET /demoapp/status/ HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: 10.39.83.235
Pragma: no-cache
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"`

I am setting my cookie with the Domain my systems IP address. Could that be getting changes through via  Emissary.

**Comment by alfrye** [comment] 2023-06-16 19:41
Hi @cindymullins-dw  I tried setting up the example that you sent me yesterday to see if I could get that working and after installing the example (https://www.getambassador.io/docs/emissary/3.1/howtos/basic-auth) in my kubernetes cluster and attempting to access it I get the following error.

`{
"message": "the example-auth.demo.1 AuthService is misconfigured; see the logs for more information",
"request_id": "15a71295-d804-41f6-bb65-ac62f6b03cc7",
"status_code": 500
}` 

I am also working on putting together a small project that includes setting a cookie the same way as my authservice is doing so you all can take a look to see if you can get it working.

**Comment by alfrye** [comment] 2023-06-20 20:09
Another question I have is that I noticed when using the AuthService that the origin header is null,  do you know if this is correct? My external authservice is using the origin header to set the cors header.

**Comment by alfrye** [comment] 2023-06-21 13:59
@cindymullins-dw  I updated my upstream application code to print out the request headers and it appears that the Set-Cookie is making it to the upstream but cookie is not being set in browser. I am setting the cookie the same 


`map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-US,en;q=0.9] Cache-Control:[no-cache] Pragma:[no-cache] Sec-Ch-Ua:["Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:["Linux"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Set-Cookie:[ALAN_SESSION=resp.ResponsToken; Path=/; Domain=10.39.83.235; Expires=Thu, 20 Jun 2024 12:35:16 GMT; Max-Age=86400; HttpOnly; Secure; SameSite=None] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36] X-Envoy-Expected-Rq-Timeout-Ms:[3000] X-Envoy-Internal:[true] X-Envoy-Original-Path:[/demoapp/status/] X-Forwarded-For:[10.42.0.1] X-Forwarded-Proto:[https] X-Myheader2:[ABC] X-Request-Id:[f41302dd-c2aa-4256-af26-0737c87b64fd]]`

Example code can be found here: https://github.com/alfrye/authdemo/tree/main/examples/demoapp

[demoapp.zip](https://github.com/emissary-ingress/emissary/files/11818455/demoapp.zip)

**Comment by alfrye** [comment] 2023-06-29 20:18
I am attaching the snapshot I took from my emissary-ingress instance
[ambassador.zip](https://github.com/emissary-ingress/emissary/files/11910179/ambassador.zip)

**Comment by cindymullins-dw** [comment] 2023-07-05 22:34
Hi @alfrye , thanks for the logs.  Having reviewed, our engineers believe Emissary is handling the cookie properly and it's likely an issue with the authService itself.  What about [this issue](https://stackoverflow.com/questions/73730172/response-header-set-cookie-doesnt-store-cookies-in-browser) - could `withCredentials = true` be at fault?

**Comment by alfrye** [comment] 2023-07-06 20:53
Hi @cindymullins-dw, thanks for the response. I think I have tried setting cors before but I will take another look at make sure I an setting Cors in the authservice. Also can you clarify whether I need to cors configuration in my emissary mappings

**Comment by alfrye** [comment] 2023-07-07 20:13
hi @cindymullins-dw  I tested again using the following cors setting on the ext auth service for the authenticate endpoint

` router.Use(cors.New(cors.Config{
	 	AllowOrigins:     []string{"https://10.39.83.235"},
	 	AllowMethods:     []string{"GET", "OPTIONS"},
	 	AllowHeaders:     []string{"Content-Type", "Content-Length", "Accept-Encoding", "Authorization", "Cache-Control", "Set-Cookie", "Origin"},
	 	ExposeHeaders:    []string{"Content-Length", "Set-Cookie"},
	 	AllowCredentials: true,
              / MaxAge:           12 * time.Hour,
	}))`

does anyone have any esample auth-service that sets a cookie?

Thanks!	// 	/

**Comment by alfrye** [comment] 2023-07-13 12:15
Update on my issue. I performed a wireshark capture while trying to access the upstream application and when the request goes through the emissary authservice I am not see the Set-Cookie header come across the wire to the client.

**Comment by cindymullins-dw** [comment] 2023-07-14 20:52
Thanks for linking to that other issue.  Based on that I did some research and found that original conversation.  I think what happens is the AuthService forwards the Set-Cookie to the upstream as a request header rather than returning it to the client as a response header.  I think the workaround, as noted, is to handle sending the cookie header back to the client by adding it to the response from the upstream or create a custom auth service with this functionality.  It's likely a limitation with Emissary.  The OAuth filter with Edge Stack provides more customization and features around client-Service communications.

**Comment by alfrye** [comment] 2023-07-14 21:01
Thanks, Cindy, I do have a custom auth service which is where the cookie is created and returned to emissary with a 200 response, and then the header is passed by emissary to the upstream as a request header. In my use case it is not feasible for all the apps in our cluster to read the header and sent it as a response. Please let me know if I using the AuthService module incorrectly.

**Comment by alfrye** [comment] 2023-07-17 21:03
hi @cindymullins-dw  After looking at your previous note (https://github.com/emissary-ingress/emissary/issues/4381#issuecomment-1636426296)  could you please clarify your  statement "creating a custom auth service with this functionality." Because the cookie is currently set in my external auth service. My understanding is that emissary ingress only allows 1 service to be running.

**Comment by alfrye** [comment] 2023-07-20 14:57
@cindymullins-dw  I was able to get the Set-Cookie header to pass properly to my upstream and the browser was able to pick it up properly. The resolution was to use the add_response_headers field in my mappings file and set the value using Envoy dynamic values. 

`add_response_headers:
    X-myheader:
      value: "1234ABC"
    Set-Cookie:
       value: "%REQ(set-cookie)%"`

Also can you use dynamic envoy values in tha ambassador module

`spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  config:
    defaults:
      httpmapping:
        add_response_headers:
          Set-Cookie: '%REQ(set-cookie)%'
    diagnostics:
      allow_non_local: true
      enabled: false
`

**Comment by cindymullins-dw** [comment] 2023-07-24 20:03
Thanks for sharing that discovery, @alfrye!  I'm sure that will be helpful to other users.  I'll close this issue as it appears to be resolved.

**Closed by cindymullins-dw** 2023-07-24 20:03 UTC
