### ISSUE TITLE
"Sampling priority locked, trace already propagated" logs when using TracingService with datadog driver.

### ISSUE THREAD

**Issue by eddy-curv** [emissary-ingress/emissary#3244] opened 2021-03-01 12:47 UTC
After upgrading Ambassador OSS from 1.6.1 to 1.9.1 there are frequent occurrences of the following log entries "Sampling priority locked, trace already propagated". From the context I suspect that it's related to TracingService miss-behaving with Nginx, I'll explain: 
We expose all of our API services using Ambassador, which itself is exposed via GCP Ingress on `/*`. A GCP healtcheck is automatically configured to the backend service (HTTP2), it makes the following Journey:
`Ambassador->ui-service.`
the ui-service is actually an Nginx that serves static content. I assume that some trace related header is passed in the request and makes Nginx return an error which causes Ambassador to print this log.

**To Reproduce**
1. Expose Ambassador OSS over GCP Ingress using HTTP2 service on path `/*`
2. Make sure that a healthcheck to the backend service is configured to `/`.
3. Define a TracingService with datadog driver (don't change any sampling related settings).
4. Define a mapping which will pass all requests to path `/` to a Nginx K8s deployment.
5. Open Ambassador logs.

**Expected behavior**
No "Sampling priority locked, trace already propagated" logs in Ambassador.

**Versions (please complete the following information):**
 - Ambassador: 1.9.1
 - Kubernetes environment: GKE 1.16 
 - NGINX nginx:1.19.5-alpine
 - Datadog as [TracingService](https://www.getambassador.io/docs/latest/topics/running/services/tracing-service/) driver (Datadog agent 7.23.0)

**Comment by sumshar-appdirect** [comment] 2022-05-02 20:16
Hi @bsamsom !

Were you able to track down the root cause of this? We're observing a similar issue and I did try reaching out to Datadog to see if this is something on their end. They came back saying they could not find any references of this error message in their agent source code.
Not sure if it's dynamically generated or if it's coming from an underlying library that ambassador/datadog-trace agent uses.

**Comment by bsamsom** [comment] 2022-05-02 20:21
I was not able to determine the cause of these logs in our ecosystem(or to hide them), we are still seeing a very large number of these logs per day.

**Comment by cindymullins-dw** [comment] 2022-07-22 16:41
Closing as appears to be a Datadog issue.

**Closed by cindymullins-dw** 2022-07-22 16:41 UTC
