### ISSUE TITLE
emissary-ingress 2.0.4 not creating envoy listeners

### ISSUE THREAD

**Issue by vjdhama** [emissary-ingress/emissary#3894] opened 2021-10-25 04:12 UTC
**Describe the bug**
On installing `emissary-ingress` through Helm chart(version `7.1.9`), which installs emissary-ingress versioned `2.0.4`, the listeners are not getting created on envoy.

**To Reproduce**
1. Install emissary-ingress using Helm chart(version `7.1.9`)
2. Using following Helm values override : 

  ```
  values:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    agent:
      enabled: false
    crds:
      enabled: true
      create: true
    createDefaultListeners: true
  ```

**Expected behavior**
Two listeners on Envoys to be created.

**Versions (please complete the following information):**
 - Ambassador: [2.0.4]
 - Kubernetes environment [EKS]
 - Version [1.19]

**Additional context**
The default listeners are getting created as CRD objects.

```
➜ kubectl get listeners.getambassador.io -A
NAMESPACE        NAME                              PORT   PROTOCOL   STACK   STATSPREFIX   SECURITY   L7DEPTH
ambassador     emissary-ingress-http-listener    8080   HTTP                             XFP
ambassador     emissary-ingress-https-listener   8443   HTTPS                            XFP
```

The generated Envoy config file.

```
➜ kubectl exec -it emissary-ingress-74cb74f84b-5h2kr -- cat envoy/envoy.json
{
  "@type": "/envoy.config.bootstrap.v3.Bootstrap",
  "layered_runtime": {
    "layers": [
      {
        "name": "static_layer",
        "static_layer": {
          "envoy.reloadable_features.enable_deprecated_v2_api": true,
          "re2.max_program_size.error_level": 200
        }
      }
    ]
  },
  "static_resources": {
    "clusters": [
      {
        "alt_stat_name": "127_0_0_1_8877",
        "connect_timeout": "3.000s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
          "cluster_name": "cluster_127_0_0_1_8877_infrastructure",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "127.0.0.1",
                        "port_value": 8877,
                        "protocol": "TCP"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "name": "cluster_127_0_0_1_8877_infrastructure",
        "type": "STRICT_DNS"
      }
    ],
    "listeners": []
  }
}
```

**Comment by felix-dpg** [comment] 2021-11-04 09:25
Any update of this????

**Comment by fransemino** [comment] 2021-11-09 22:18
Same problem Here @felix-dpg . any workarround?

**Comment by jmeza-xyz** [comment] 2021-11-10 04:20
Hi @vjdhama @felix-dpg, by chance are you setting the `ambassador_id` env variable in the helm chart? If you are, then that might be your issue. The default listeners don't have an option to set ambassador_id and you need to edit that in manually. If you can share your helm chart values (excluding sensitive data) plus the host/listener/mapping values, that would be helpful as well.

Also, side note, the listeners won't be picked up without a Host/Mapping that matches with your Listener crd.

**Comment by isaac88** [comment] 2021-11-30 23:16
I just installed the latest version 2.0.4 and I have the same issue. 
It was working properly fine in the previous version 1.14.0
The Envoy listeners doesn't start properly in the 8080 and 8443.
any clue on that @jmeza-xyz ?

**Comment by felix-dpg** [comment] 2021-12-01 07:43
The problem is the image, use datawire/emissary:2.0.4, the docs come with this docker.io/emissaryingress/emissary:2.0.5 that fail with the error of this issue.

**Comment by isaac88** [comment] 2021-12-01 10:14
@felix-dpg I tested that image datawire/emissary:2.0.4 also and I still having the same issues.
I can see in the logs : 
`No active listeners at all; check your Listener and Host configuration`
Do you know what is missing ? 
In the previous version 1.14.0 was working fine but now I can see that Envoy doesn't start the listener. 
 `    "listeners": []`

**Comment by kflynn** [comment] 2021-12-01 18:19
Hi @vjdhama @felix-dpg –

A major difference between Emissary 1.X and Emissary 2.X is that Emissary 2.X introduces [the `Listener` CRD](https://www.getambassador.io/docs/emissary/latest/topics/running/listener/). The point of the `Listener` CRD is to tell Emissary exactly where you want to listen for what, and it _must_ be present for Emissary 2.X to listen for any traffic. 

When you install with Helm, you can set `createDefaultListeners` to tell Helm to create `Listener`s for ports 8080 and 8443, if you like. When you install manually, you need to create `Listener`s manually too.

We talk about this in the "Changes in 2.0" document (https://www.getambassador.io/docs/emissary/latest/about/changes-2.0.0/#2-listeners-hosts-and-mappings) and in the Helm chart's README (https://github.com/emissary-ingress/emissary/blob/master/charts/emissary-ingress/README.md). Where else would be good for us to talk about it?

**Comment by isaac88** [comment] 2021-12-01 18:35
Hello @kflynn @felix-dpg 

I've installed it using Helm `createDefaultListeners: true` and I can see that the CRD Listeners are created but it doesn't start in the /envoy/envoy.conf.

`
kubectl get listeners.getambassador.io
NAME                                               PORT   PROTOCOL   STACK   STATSPREFIX   SECURITY   L7DEPTH
emissary-ingress-http-listener     8080    HTTP                                                      XFP
emissary-ingress-https-listener   8443    HTTPS                                                    XFP
`

There are something else that I miss ?

Thanks

**Comment by isaac88** [comment] 2021-12-01 20:11
Hello @kflynn @felix-dpg

Finally I found my issue.
The problem was that I was setting the env var `AMBASSADOR_LABEL_SELECTOR` then when the Listener CRD is created Emissary Ingress is not taking in consideration that object so Envoy can't be configured properly.

I hope that it can help for others. 

Thanks a lot.

**Comment by kflynn** [comment] 2021-12-01 20:31
@isaac88 That's great news, thanks for posting!

**Comment by kflynn** [comment] 2022-03-04 18:19
Closing, since the issue ultimately was the `AMBASSADOR_LABEL_SELECTOR` rather than Emissary.

**Closed by kflynn** 2022-03-04 18:19 UTC
